### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by SBS-jtemplin**
# Description

* Fix typo and broken link
* Add license to pyproject.toml
* Add .gitattributes

Closes: NA

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Select the type of tests you added for these changes

- [ ] Unit
- [ ] Integration
- [ ] Component
- [ ] E2E
- [ ] User

## Did you test these changes on all platforms (if applicable to the JIRA item?)

- [ ] Windows
- [ ] MacOS

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have cleared any run data/output from the ipynb file(s)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] My code is up to date with the branch I'm requesting to merge into

### CODE REVIEW

**Comment by SBS-jtemplin** [comment]
```
seabirdscientific/
|
├── documentation/
|   ├── example_data/          [sample data files]
|   ├── ctd-processing.ipynb   [CTD Jupyter notebook]
|   ├── ctd-notebook.pdf       [static pdf notebook]
|   └── ctd-notebook.html      [static html notebook]
|
├── src/
|   └── sbs/
|       ├── process/           [processing modules]
|       └── visualize/         [visualization modules]
|
├── tests/                     [unit tests]
|
└── README.md
```

Since the readme is shared between github and pypi, how do we want to define the hierarchy here? As @SBS-EREHM pointed out, `documentation` and `tests` are not included in the package installed by pip, which only includes `sbs`

**Comment by SBS-jtemplin** [comment]
@SBS-BRhoades - I'm more inclined to just remove the section altogether. A user viewing the repo on github will have already scrolled past the actual folders to see the folder tree, and github provides a pretty good file browser-like interface when clicking on a folder

**Review by SBS-dlucas — APPROVED** [review]

**Comment by SBS-jtemplin** [comment]
@SBS-dlucas - Since you're approving, what's your opinion on the file tree?

**Comment by SBS-EREHM** [comment]
> @SBS-dlucas - Since you're approving, what's your opinion on the file tree?

Weighing in here too:  I agree with @SBS-BRhoades that we should remove that section.

However, it might be nice to add some data prerequisites for using the toolkit, namely you'll need:
- CTD data in .hex format along with knowledge of what sensors are enabled in the data.  (See class Sensors() in instrument_data.py)
- calibration coefficients for each sensor that is enabled.  See convert_* functions in conversion.py.

**Comment by SBS-jtemplin** [comment]
@SBS-EREHM - Thanks for the feedback. I've added pypi sidebar links to seabird's software page and the github repo, and replaced the file tree with a link to the docs. I'll create a ticket for adding prerequisites to the docs. As for the cnv function, it was never really intended for production. I wrote it to compare the toolkit's processing functions to their corresponding SeaSoft functions, since after the initial hex conversion SeaSoft only returns .cnv files. As is, I agree it's a bit unfinished

**Comment by SBS-EREHM** [comment]
@SBS-jtemplin fyi I don't see those changes yet on PyPI. I'm already pointing customers to the package and repo.

**Pull request merged**
